apiVersion: app/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec: 
  replicas: 1
  selector:
    matchLables:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: poojithkumar29/mongodb:v1

